# Generated by Django 5.1.3 on 2025-04-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(max_length=255)),
                ('response', models.TextField(blank=True, null=True)),
                ('ai', models.CharField(choices=[('SC', 'StarCoder'), ('OL', 'Ollama'), ('AI', 'Unknown')], default='AI', max_length=2)),
            ],
        ),
    ]
