# Generated by Django 5.1.3 on 2025-01-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starcoder', '0002_prompt_ai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
