# Generated by Django 5.1.3 on 2025-01-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ollama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='ai',
            field=models.CharField(choices=[('SC', 'StarCoder'), ('OL', 'Ollama'), ('AI', 'Unknown')], default='AI', max_length=2),
        ),
    ]
