# Generated by Django 5.1.3 on 2025-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generated_Html',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('prompt', models.TextField(max_length=255)),
                ('html_code', models.TextField(blank=True, null=True)),
                ('ai', models.CharField(choices=[('SC', 'StarCoder'), ('OL', 'Ollama'), ('OP', 'OPENAI'), ('DK', 'DeepSeek'), ('UN', 'Unknown')], default='UN', max_length=2)),
            ],
        ),
    ]
