# Generated by Django 5.1.1 on 2025-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_renderizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generated_html',
            name='ai',
            field=models.CharField(choices=[('SC', 'StarCoder'), ('OL', 'Ollama'), ('OP', 'OPENAI'), ('GE', 'Gemini'), ('CS', 'Cursor'), ('CE', 'Claude'), ('UN', 'Unknown')], default='UN', max_length=2),
        ),
    ]
